// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "7eed01dc4cec5d4ac51cb00153bcfcbe9d56b4072364759599b6c79a59e73dd8")
