// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "88fe5cab7cad5eae712ca0b1ef73f16652123e1577fca9e1b0c01c82d10e43ea")
