// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "a957d3120bd94f19e7b47d620985fbf4c8a693be917cc2d87d514357897f1dfe")
